from datetime import datetime, timezone

from app.schemas import Message
from app.services.chatbox import ChatboxChatAgent, ChatboxChatAgentConfig


class FakeClient:
    def __init__(self) -> None:
        self.messages: list[dict[str, str]] | None = None

    def chat(self, messages: list[dict[str, str]]) -> str:
        self.messages = messages
        return "Generated by migrated service"


def make_message(role: str, content: str) -> Message:
    return Message(
        id=f"{role}-1",
        conversation_id="conv-1",
        role=role,
        content=content,
        created_at=datetime.now(timezone.utc),
    )


def test_chatbox_agent_builds_openai_messages_from_conversation():
    client = FakeClient()
    agent = ChatboxChatAgent(
        ChatboxChatAgentConfig(test_mode=False),
        client=client,
    )

    result = agent.reply_from_conversation(
        [
            make_message("user", "I am having trouble sticking to a sleep routine."),
            make_message("assistant", "What part of your evening feels hardest to change?"),
        ]
    )

    assert result == "Generated by migrated service"
    assert client.messages is not None
    assert client.messages[0]["role"] == "system"
    assert "behavioral health coach named David" in client.messages[0]["content"]
    assert client.messages[-1]["role"] == "user"
    assert "I am having trouble sticking to a sleep routine." in client.messages[-1]["content"]


def test_chatbox_agent_formats_recent_history_like_migrated_service():
    agent = ChatboxChatAgent(ChatboxChatAgentConfig())

    history_text = agent.format_recent_history(
        [
            make_message("user", "I want to sleep earlier."),
            make_message("assistant", "What time are you going to bed now?"),
            make_message("user", "Usually around 1 AM."),
        ]
    )

    assert "User: I want to sleep earlier." in history_text
    assert "Assistant: What time are you going to bed now?" in history_text
    assert "User: Usually around 1 AM." in history_text


def test_chatbox_agent_build_messages_from_text_supports_prompt_patch_and_memory():
    agent = ChatboxChatAgent(ChatboxChatAgentConfig(include_fewshot=False))

    messages = agent.build_messages_from_text(
        user_input="I feel stuck.",
        prompt_patch="FOCUS: sleep",
        memory_text="Last session report: bedtime target was 11:30 PM.",
        recent_history_text="Recent chat history:\nUser: I stayed up late again.",
    )

    assert messages[0]["role"] == "system"
    assert "behavioral health coach named David" in messages[0]["content"]
    assert messages[1] == {"role": "system", "content": "FOCUS: sleep"}
    assert messages[2]["content"] == "Last session report: bedtime target was 11:30 PM."
    assert "Recent chat history:" in messages[3]["content"]
    assert messages[4] == {"role": "user", "content": "I feel stuck."}


def test_chatbox_agent_test_mode_returns_friendly_stub():
    agent = ChatboxChatAgent(ChatboxChatAgentConfig(test_mode=True))

    result = agent.reply_from_conversation(
        [make_message("user", "I feel behind on everything this week.")]
    )

    assert "I hear you saying" in result
    assert "behind on everything this week" in result
